spring.application.name=pedido-service
server.port=8082

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

#Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#Database
spring.datasource.url=jdbc:mysql://localhost:3306/db_pedido_service
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Microservicios
microservices.usuario.base-url=http://localhost:8080
microservices.producto.base-url=http://localhost:8081

#Control de loggs
logging.level.root=INFO
logging.level.com.lovable.pedido_service=DEBUG